# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: d627c3204b4b9c952c81752d277263b3a5f2ac211186f4b8a8c81d876dd9390547374f8469a52043b78d074a28272692edb913f5c69b24b89c2ef2a0507f126d

test:
  secret_key_base: e134ba3ea3d0de0fd63d64b45b39e803b1aa6190f66ee66906ade2db09af3b9846d325b622875d20d6bb1d291544ec1338a4068a5d9577712865cb9b0da8b0a5

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
